name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs-version:
          - 28.1
          - 28.2
          - 29.1
    steps:
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/checkout@v2
      - uses: emacs-eldev/setup-eldev@v1
      - run: make doctor
      - run: make lint
      - run: make compile
      - run: make test
