name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs-version:
          - 28.1
          - 28.2
          - 29.1
    steps:
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/checkout@v2
      - uses: emacs-eldev/setup-eldev@v1
      - run: make lint
      - run: make compile
      - run: make test
        env:
          COVERALLS_FLAG_NAME: run-${{ join(matrix.*, '-') }}
          COVERALLS_PARALLEL: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  finish:
    if: ${{ always() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
