name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        emacs-version:
          - 29.1
    steps:
      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/checkout@v2
      - uses: emacs-eldev/setup-eldev@v1
      - run: make lint
      - run: make compile
      - run: make test
        env:
          COVERALLS_FLAG_NAME: ${{ join(matrix.*, '-') }}
          COVERALLS_PARALLEL: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish:
    if: ${{ always() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
